### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by k-bx** [informatikr/hedis#184]
subj

See also: https://discourse.haskell.org/t/looking-for-maintainers-hedis-and-servant-elm/4616

**Comment by k-bx** [comment]
Hey @info

**Comment by informatikr** [comment]
Done. Welcome and thanks @jbrechtel. Let me know if everything works for you.

**Comment by qnikst** [comment]
Hello, the company I'm working at making heavy use on Redis and Hedis library.

So if there are no objections I'm personally or as a company we are ready to volunteer to co-maintaining the library. We are mostly interested in redis-7 support, stream support and general effiency and API clarity. However we are not using redis cluster, so we are lacking experience in that field.

**Comment by ysangkok** [comment]
See @qnikst's comment above, @aravindgopall. Just tagging you in case you're not subscribed.

**Comment by qnikst** [comment]
Thanks a lot!

**Comment by ysangkok** [comment]
You're still not a [maintainer on Hackage](https://hackage.haskell.org/package/hedis/maintainers/), @qnikst . Would make sense if you were added there too.
